name: 8b8tPVP
version: ${project.version}
main: me.sevj6.pvp.PVPServer
authors: [ SevJ6, 254n_m ]
description: Main plugin for 8b8tpvp hosted by leee developed by SevJ6 and 254n_m
load: POSTWORLD
commands:
  clear:
    description: clear all arenas
  arenatest:
  arenalist:
  arenacreate:
  arenaremove:
  wand:
  kill:
  createportal:
  removeportal:
  portallist:
  kitcreator:
  rot:
    aliases:
      - kc
  hub:
    aliases:
      - spawn
